framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed
    
    serializer:
      default_serializer: messenger.transport.symfony_serializer
      symfony_serializer:
        format: json
        context: { }
    
    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      rabbitmq: '%env(MESSENGER_TRANSPORT_DSN)%'
      
      notifications:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          exchange:
            name: 'notifications'
            type: 'fanout' # default is 'fanout'
          queues:
            notification.email:
            notification.telegram:
            # auto_setup: true # creates the 
      # failed: 'doctrine://default?queue_name=failed'
      #            sync: 'sync://'
      
      first_redis_queue:
        dsn: '%env(REDIS_MESSENGER_TRANSPORT_DSN)%'
        options:
          serializer:
            format: json

      ivan_redis_queue:
        dsn: '%env(REDIS_MESSENGER_TRANSPORT_DSN)%'
        options:
          serializer:
            format: json
    routing:
      # Route your messages to the transports
        App\Message\MyMessage: rabbitmq
        App\Message\IvanMessage: ivan_redis_queue
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
