version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - crypto-network

  nginx:
    image: nginx:stable-alpine
    container_name: app-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - main_crypto_nginx_logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - crypto-network

  mysql:
    image: mysql:8.4
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - main_crypto_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crypto-network

  redis:
    image: redis:8.6
    container_name: app-redis
    ports:
      - "6379:6379"
    networks:
      - crypto-network

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: app-rabbitmq
    ports:
      - "5672:5672" # Default AMQP port for client connections
      - "15672:15672" # Default port for the management console UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - main_crypto_rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - crypto-network

volumes:
  main_crypto_mysql:
  main_crypto_nginx_logs:
  main_crypto_rabbitmq:

networks:
  crypto-network:
    name: crypto-network
    driver: bridge
